{% set name = "s3fs" %}
{% set version = "2024.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b8bc8dbd65e7b60f5487378f6eeffe1de59aa72caa9efca6dad6ab877405487

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - aiobotocore >=2.5.4,<3.0.0
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - fsspec {{ version }}

test:
  imports:
    - s3fs
  requires:
    - pip
  commands:
    - pip check

about:
  description : |
    S3FS builds on aiobotocore to provide a convenient Python filesystem interface for S3.
  home: https://s3fs.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
