{% set version = "0.5.0" %}

package:
  name: s3fs
  version: {{ version }}

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: d187f21b42d81ed60e89f17e7680cf0ce57adc57e6ccc371923d146b0e904cb4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python >=3.5
    - setuptools
    - boto3
    - pip

  run:
    - python >=3.5
    - boto3
    - fsspec >=0.6.0


test:
  imports:
    - s3fs

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
