{% set version = "2022.1.0" %}

package:
  name: s3fs
  version: {{ version }}

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 6bafc1f6b4e935ea59512c0f38d5cb9c299dbbfe738e40c3d1de8f67b4ee1fd4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel

  run:
    - python >=3.6
    - aiobotocore ==2.1.0
    - aiohttp >=3.7.1,<4
    - fsspec {{ version }}

test:
  imports:
    - s3fs
  requires:
    - pip
    - python <3.10
  commands:
    - pip check

about:
  home: https://s3fs.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
