{% set version = "0.2.1" %}
 
package:
  name: s3fs
  version: "{{ version }}"

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 2146aae91ba3a06d7bfa7130688219599f8696d2825fb00f62923bb56f6e7ed3

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - boto3
    - pip

  run:
    - python
    - boto3


test:
  imports:
    - s3fs

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: 'Convenient Filesystem interface over S3'

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
