{% set version = "0.3.5" %}

package:
  name: s3fs
  version: "{{ version }}"

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: f1d8d80ae7789e6c95f8432e3ec12d1c28e624aecf8c84afed373fb182b505ab

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.5
    - setuptools
    - boto3
    - pip

  run:
    - python >=3.5
    - boto3
    - fsspec


test:
  imports:
    - s3fs

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: 'Convenient Filesystem interface over S3'
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
