{% set name = "s3fs" %}
{% set version = "2022.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fsspec/s3fs/archive/refs/tags/2022.11.0.tar.gz
  sha256: 8957b7e1acadf00e9201da6386d55593ce6478a3b392a1d06c3758bbf78ece5d

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - aiobotocore 2.4.*
    - fsspec =={{ version }}
    - aiohttp !=4.0.0a0,!=4.0.0a1

# This tests failed when trying to create the bucket in the S3 mock moto_server
# botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://127.0.0.1:5555/test"
{% set ignore_tests = " --ignore=s3fs/tests/test_mapping.py" %}
{% set ignore_tests = ignore_tests + " --ignore=s3fs/tests/test_s3fs.py" %}

test:
  source_files:
    - s3fs
    - pytest.ini
  imports:
    - s3fs
  commands:
    - pip check
    - pytest -v {{ ignore_tests }}
  requires:
    - pip
    - pytest >=4.2.0
    - urllib3
    - requests
    - moto >=4
    - flask

about:
  description : |
    S3FS builds on aiobotocore to provide a convenient Python filesystem interface for S3.
  home: https://s3fs.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
