{% set version = "2023.4.0" %}

package:
  name: s3fs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 5c154ded38e3c3d8f0eba7fec2706f29b41e0c395f19fbfef3ba8e70c685b049

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - aiobotocore >=2.4.2,<2.5
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - fsspec {{ version }}

test:
  imports:
    - s3fs
  requires:
    - pip
  commands:
    - pip check

about:
  description : |
    S3FS builds on aiobotocore to provide a convenient Python filesystem interface for S3.
  home: https://s3fs.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
