{% set version = "2022.10.0" %}

package:
  name: s3fs
  version: {{ version }}

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: e8deb80f20bd0b2059141b874fdb9d6aeb8cce35312ea5f2c02b225a78a00406

build:
  skip: True #[py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel

  run:
    - python
    - aiobotocore ==2.4.0
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - fsspec {{ version }}

test:
  imports:
    - s3fs
  requires:
    - pip
  commands:
    - pip check

about:
  description : |
    S3FS builds on aiobotocore to provide a convenient Python filesystem interface for S3.
  home: https://s3fs.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt
  license_url: https://github.com/fsspec/s3fs/blob/{{ version }}/LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/en/latest/
  doc_source_url: https://github.com/fsspec/s3fs/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
