{% set version = "0.1.2" %}
 
package:
  name: s3fs
  version: "{{ version }}"

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: fba2471624b9840f050afb6d83eaec5e9b463dc497206532fa2b5590b7b58117

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - boto3

  run:
    - python
    - boto3


test:
  imports:
    - s3fs

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: 'Convenient Filesystem interface over S3'

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
