{% set name = "s3fs" %}
{% set version = "2025.3.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fsspec/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: bb3d8fa578e4f27876249eab2a53abf134a78463c9f7a6b87ad0f0886cbae1fe

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - aiobotocore >=2.5.4,<3.0.0
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - fsspec {{ version }}

# Separators error on windows:
# E -     'C:\\cygwin64\\tmp\\pytest-of-builder-admin\\pytest-4\\test_get_directory_recursive1\\target\\file',
# E ?        ^^        ^^   ^^                       ^^        ^^                             ^^      ^^...
{% set ignore_tests = "" %}
{% set ignore_tests = " --ignore=s3fs/tests/derived/s3fs_test.py" %}  # [win]
{% set ignore_tests = ignore_tests + " --ignore=s3fs/tests/test_s3fs.py" %}  # [win]

test:
  source_files:
    - s3fs
  imports:
    - s3fs
  commands:
    - pip check
    # >  fs.pipe_file(fs_target, b"data", mode="create")
    # E  Failed: DID NOT RAISE <class 'FileExistsError'>
    - pytest -v {{ ignore_tests }} -k "not (test_pipe_exclusive)" s3fs/tests
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - requests
    - moto >=4

about:
  description : |
    S3FS builds on aiobotocore to provide a convenient Python filesystem interface for S3.
  home: https://s3fs.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
