travis:
  secure:
    BINSTAR_TOKEN: GUUy6LUXHThcVan8qamwX99ffBSzafLEIm3dbYeAOuLkuOT9Z42XvVaGuwlLMVrB0p9qMcT+WToKwXQWK6sOJ2vk1xfCni3kwXRBT03x3dwUuDpYtucnNjpFsrVxYIie4IVsWNl+G1xRwwNPuohBTWAQfUFeyyBnnaL+zCCNAF1nHOweNyOEcyS6sma7A7KtaaP79N58TOHP51T30fnOzDZ5xWfpznsMnasz0nFXp4bwwQogsZvq0CbkwIqJrnB789sPFF1svPDGsEwo5p+BS9z5nKlAkOECQIRbxnXUYG13DlEvLJy2PB8JX5Zfan9dX8KCGjRN4i4tlr/Ik0m1a0wti0s1ifODsdKiezcLhF3QMI8wlef9jOkzdXrcNz3BXooed1zVcDoN1L8NCE49AYHq5obRzaWikT1mt20hynmgJdiFiRv2+OKoRIdojJN+9DlxOctQhyszEWwgYEqCGvIBMoIZxKrCcXF4ARCmPmNNKg19Qzam5VyUlJfKMqfqTrOixEWMslwpjBO5YNlqMD89cN57Ctyc9iES6IIYpwLrmVUVODkyOdtgd50x/TmIwLDlngzWwtq91OXplK7Xcti0+rHDEN5GK8aHk2srs02YU/SoV5C4R5e+pq1cgVQ97dJabNs2F8UIDkMcLClp6+ZSjjXg6XrOrKPsjfatiZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
