travis:
  secure:
    BINSTAR_TOKEN: FneUL2wmoKDETHt5tJPwXV87avMJJ+lg00oh6eAE6qGDziJ6RNV84nDTQG2aVHHXUFGEfhRvS5PsNqfTbMuk0dS0xtC37Z7hlOQvOXC80KNcFcoIfwdH5N86qkxKGmtotM4aQ2uO4vnaf72XPJSBYxTl+5oZsSaRUzwqRug00XEYka0U6vMN4X2Pqe1jBYYZ3V1qaRPaRh3fcKloeOOZS9rJ5mKtn6cazaj6i8XTyO9PmUrHWs3x+5Umns8z/9L/u0XvvW3cLNcScu8C+YjFC5Pu8+Fqp6PZLyoilcdVDsYpQOz8qUjxeqx0SPiygnkaYje1t49VBSwlFb/cXSHOdHVqffL4kUY2Dy5RIiWU87Sfd1vybbhJd3rpkt8R3Ay2UEuGmL4u0x9oCwFrpB/SB45XkQYSHETfzl/5c5oSkfCGR9LCffJZ9Co5KPBygOLlp2jBpvnAlyiqWXcmHhlqpjXOJ2y78bC/VtKqKQcUVXxF1cd5cAFSdLCl3pbYE4BronQB7UNJ+zxWe8nOsuU2n6i8/27G+frNQLJDuXUKkE3NRvvaKMmmzouVlJIEzBHeyPNyc0sXQvsaBZe2B3i7vlwmwXmSu5ddYHP52asyRcxyacNzubqmLHmVpvjpe9crbR2YHJ3ztAmwYZQL/xpg5aQErjVm0r0igv5QUuCmYKU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
