travis:
  secure:
    BINSTAR_TOKEN: JPhlbTSLgRdarjUJuKtA510L4icN5Ged9sfv08X5dR6yEH6Y7ZjoFKxqsi/YqtPogos709beV3IcgFoY01ytWUpdg5dLDY251raJOu/RSHSMvtaBT7x7WqRn0Hc6JulnH7iJbQkdfeOi91KOLLFyl3wcETO/t3ZvEDs8ML9yHH6khW+ltv1qiNQLE9gR7jR3pXSPz/DH0+AnxDGlfQJ+e3vrlDlBKrvltO+4j2XfDD9prLUItudyFaBYV0j+jGhW/JHuQDglbKA1C4JRV7nLl+0jff8ahyc0WUlrt0JYP1f1ObedpKKb+cId6qfE02m3B8k5QQhZO1+Zq/2q2jtyNIc4p3fQCJsM8M/PU2oyQUVkoSMkksnD395srcjA5UnFTBFSteLhzM9jT5FmgmP5kmZw19APsbc4KofBQNH0B1CHo2OU/JNh6+cOGAg8BPXbfS9GZB4huUiLo3UUbiR0lkyjS4yApqEsval9dpyCyrw3ClqDgL2fUqtbB3QKOMs85QV1gEhNrXrjD/TWQjn3HiAwE4q2Fj28U9GFeIJXN7vFXGcsjoGDkil4iNzVGc+BzEcdQLPv8BN/BVSzNQHCu1+3bCYGwV3vJKe4syYKmf0QW3p3vHqycP98OoGhWECNFg4RZWsvrGgq5pjcD6/DuyQNHfjKooAqHtkFUMINJhQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
